[package]
name = "xboxlive-auth"
version = "0.1.0"
edition = "2018"

[dependencies]
regex = "1.5"
reqwest = { version = "0.11", features = ["cookies", "json", "blocking"] }
anyhow = "1.0"
serde_json = "1.0.64"
structopt = "0.3"
