[package]
name = "xboxlive-auth"
version = "0.2.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
regex = "1.5"
reqwest = { version = "0.11", features = ["cookies", "json", "blocking"] }
serde_json = "1.0"

[profile.release]
lto = true
codegen-units = 1
